server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location_service_db
    username: location_service_admin
    password: your_secure_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: development

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,prometheus
  prometheus:
    enabled: true

my-service:
  message: Hello from Default Profile!

# Removed duplicate 'spring:' block here. Only one 'spring:' block in the first document.

