server:
  port: 8080

# All Spring-related properties are nested under a single 'spring' key
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: development

# All management properties are nested under a single 'management' key
management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,prometheus
  prometheus:
    enabled: true

my-service:
  message: Hello from Default Profile!

---
# This section for profile-specific overrides remains the same
spring:
  config:
    activate:
      on-profile: "development,production"

my-service:
  message: Hello from a non-default profile!