apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "team-evil-jenkins.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "team-evil-jenkins.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
      annotations:
        redeploy-timestamp: "{{ .Values.redeploy | default "" }}"
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      serviceAccountName: {{ include "team-evil-jenkins.serviceAccountName" . }}
      securityContext:
        {{- .Values.client.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: client
          securityContext:
            {{- .Values.client.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.ghcr.registry }}/{{ .Values.ghcr.organization }}/{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          env:
            - name: VITE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_DOMAIN
            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_CLIENT_ID
            - name: VITE_AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_AUDIENCE
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- .Values.client.resources | toYaml | nindent 12 }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
