{{- if .Values.genai.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: genai
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
spec:
  type: {{ .Values.genai.service.type }}
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "team-evil-jenkins.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai
{{- end }}
