{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "team-evil-jenkins.fullname" . }}-main
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    - host: {{ .Values.ingress.client.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.client.path }}
            pathType: {{ .Values.ingress.client.pathType }}
            backend:
              service:
                name: client
                port:
                  number: 80
    - host: {{ .Values.ingress.api.host | quote }}
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
          - path: /locations
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
          - path: /genai
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
{{- end }}
