apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: location-service
spec:
  type: {{ .Values.locationService.service.type }}
  ports:
    - port: {{ .Values.locationService.service.port }}
      targetPort: http # Assumes the container port is named 'http' in the Deployment
      protocol: TCP
      name: http
  selector:
    {{- include "team-evil-jenkins.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: location-service
