apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-evil-jenkins.fullname" . }}-matching-service
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: matching-service
spec:
  type: {{ .Values.matchingService.service.type }}
  ports:
    - port: {{ .Values.matchingService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "team-evil-jenkins.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: matching-service
