apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: matching-service
spec:
  replicas: {{ .Values.matchingService.replicaCount }}
  selector:
    matchLabels:
      {{- include "team-evil-jenkins.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: matching-service
  template:
    metadata:
      labels:
        {{- include "team-evil-jenkins.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: matching-service
      annotations:
        redeploy-timestamp: "{{ .Values.redeploy | default "" }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "team-evil-jenkins.serviceAccountName" . }}
      securityContext:
        {{- .Values.matchingService.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: matching-service
          securityContext:
            {{- .Values.matchingService.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.ghcr.registry }}/{{ .Values.ghcr.organization }}/{{ .Values.matchingService.image.repository }}:{{ .Values.matchingService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.matchingService.service.port }}
              protocol: TCP
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-service:5432/matching_service_db"
          - name: SPRING_DATASOURCE_USERNAME
            value: "admin"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "your_secure_password"
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- .Values.matchingService.resources | toYaml | nindent 12 }}
      {{- with .Values.matchingService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.matchingService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.matchingService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
