apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-evil-jenkins.fullname" . }}-messaging-service
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging-service
spec:
  type: {{ .Values.messagingService.service.type }}
  ports:
    - port: {{ .Values.messagingService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "team-evil-jenkins.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: messaging-service
