apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "nginx/nginx.conf" | indent 4 }}
  oidc.lua: |
{{ .Files.Get "nginx/oidc.lua" | indent 4 }}
