apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway-deployment
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-gateway
spec:
  replicas: {{ .Values.nginxGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "team-evil-jenkins.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx-gateway
  template:
    metadata:
      labels:
        {{- include "team-evil-jenkins.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx-gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx-gateway
          image: "{{ .Values.ghcr.registry }}/{{ .Values.ghcr.organization }}/{{ .Values.nginxGateway.image.repository }}:{{ .Values.nginxGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: AUTH0_DOMAIN
              value: "{{ .Values.nginxGateway.auth0.domain }}"
            - name: AUTH0_AUDIENCE
              value: "{{ .Values.nginxGateway.auth0.audience }}"
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_SECRET
          resources:
            {{- .Values.nginxGateway.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/oidc.lua
              subPath: oidc.lua
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-gateway-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: oidc.lua
                path: oidc.lua
