apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  labels:
    {{- include "team-evil-jenkins.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "team-evil-jenkins.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-gateway
