services:
  user-service:
    build:
      context: ./server/userservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  location-service:
    build:
      context: ./server/locationservice
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  client:
    build: ./client
    ports:
      - "3000:80"

# TODO:
# othe-service: