services:
  user-service:
    build: ./server/userservice
    ports:
      - "8080:8080" # TODO: should mapping be defined here ? 

  client:
    build: ./client
    ports:
      - "3000:80"
    

# TODO:
# othe-service: