services:
  user-service:
    build: ./server/userservice
    ports:
      - "8080:8080" # TODO: should mapping be defined here ? 

  matching-service:
    build: ./server/matchingservice
    ports:
      - "8081:8080"

  messaging-service:
    build: ./server/messagingservice
    ports:
      - "8082:8080"

  client:
    build: ./client
    ports:
      - "3000:80"

  genai-service:
    build: ./genai
    ports:
      - "8000:8000"

# TODO:
# othe-service:
