services:
  user-service:
    build:
      context: ./server
      dockerfile: userservice/Dockerfile
    ports:
      - "8080:8080"

  location-service:
    build:
      context: ./server
      dockerfile: locationservice/Dockerfile
    ports:
      - "8081:8080"

  client:
    build: ./client
    ports:
      - "3000:80"

# TODO:
# othe-service: