# Global values can be defined here

# Namespace configuration
namespace:
  name: team-evil-jenkins 
  create: false 


imagePullPolicy: Always

# Secrets for pulling images from private registries like GHCR
imagePullSecrets:
  - name: ghcr-creds # This should match the name of the secret you create in Kubernetes

# GHCR image registry
ghcr:
  registry: ghcr.io
  organization: aet-devops25 

client:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/client
    tag: latest 
  service:
    type: ClusterIP 
    port: 80 

userService:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/user-service
    tag: latest
  service:
    type: ClusterIP
    port: 8080 # Container port

locationService:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/location-service
    tag: latest
  service:
    type: ClusterIP
    port: 8080 # Container port 

messagingService:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/messaging-service
    tag: latest
  service:
    type: ClusterIP
    port: 8080 # Container port

matchingService:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/matching-service
    tag: latest
  service:
    type: ClusterIP
    port: 8080 # Container port

serviceAccount:
  create: false
  annotations: {}

# Configuration for the GenAI service
nginxGateway:
  replicaCount: 1
  image:
    repository: team-evil-jenkins/nginx-gateway
    tag: latest
  resources: {}

genai:
  enabled: true
  replicaCount: 1
  image:
    repository: team-evil-jenkins/genai
    tag: latest
  service:
    type: ClusterIP
    port: 80 # Service port
  resources: {}
  env: 
    OPENWEBUI_URL: ""
    OPENWEBUI_API_KEY: ""

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - team-evil-jenkins.student.k8s.aet.cit.tum.de
      secretName: team-evil-jenkins-tls
    - hosts:
        - api.team-evil-jenkins.student.k8s.aet.cit.tum.de
      secretName: team-evil-jenkins-api-tls
  client:
    host: team-evil-jenkins.student.k8s.aet.cit.tum.de
    path: /
    pathType: Prefix
  api:
    host: api.team-evil-jenkins.student.k8s.aet.cit.tum.de
 

