global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080'] 

  - job_name: 'location-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['location-service:8080'] 

  - job_name: 'matching-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['matching-service:8080'] 

  - job_name: 'messaging-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['messaging-service:8080'] 

  - job_name: 'client'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['client:8080'] 

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai:8000'] 