{{- if .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-grafana-pvc" (include "monitoring-chart.fullname" .) }}
  labels:
    {{- include "monitoring-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.grafana.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.grafana.persistence.storageClassName }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  {{- end }}
{{- end }}