apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-chart.fullname" . }}-prometheus-config
  labels:
    {{- include "monitoring-chart.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    {{- toYaml .Values.prometheus.config | nindent 4 }}
