apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring-chart.fullname" . }}-prometheus-deployment
  labels:
    {{- include "monitoring-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      annotations:
        redeploy-timestamp: "{{ .Values.redeploy | default (now | date "2006-01-02T15:04:05Z07:00") }}"
      labels:
        {{- include "monitoring-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: storage-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "monitoring-chart.fullname" . }}-prometheus-config
        - name: storage-volume
          emptyDir: {}
