# values.yaml for monitoring-chart

fullnameOverride: "monitoring"

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.52.0
  service:
    type: ClusterIP
    port: 9090
  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'user-service'
        metrics_path: '/api/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8080']
      - job_name: 'location-service'
        metrics_path: '/api/actuator/prometheus'
        static_configs:
          - targets: ['location-service:8080']
      - job_name: 'matching-service'
        metrics_path: '/api/actuator/prometheus'
        static_configs:
          - targets: ['matching-service:8080']
      - job_name: 'messaging-service'
        metrics_path: '/api/actuator/prometheus'
        static_configs:
          - targets: ['messaging-service:8080']

grafana:
  smtp:
    enabled: true
    host: "smtp.example.com:587"
    user: "your-email@example.com"
    from_address: "grafana@example.com"
    from_name: "Grafana Alerts"
    existingSecret: "grafana-smtp-secret"
    secretKey: "GF_SMTP_PASSWORD"

  image:
    repository: grafana/grafana-oss
    tag: latest
  service:
    type: ClusterIP
    port: 3000
  provisioning:
    notifiers:
      enabled: true
      config:
        - name: 'Evil Jenkins hook'
          type: 'webhook'
          uid: 'my-webhook-notifier' #
          is_default: true
          settings:
            url: 'https://webhook.site/e1a8849e-2dcd-4164-ab7b-94495b56039f'

    enabled: true
    datasource:
      name: Prometheus
      type: prometheus
      access: proxy
      url: http://monitoring-prometheus-service:9090
      isDefault: true
  dashboard:
    enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    grafana: "grafana-team-evil-jenkins.student.k8s.aet.cit.tum.de"
    prometheus: "prometheus-team-evil-jenkins.student.k8s.aet.cit.tum.de"
  tls:
    - secretName: monitoring-tls-secret
      hosts:
        - grafana-team-evil-jenkins.student.k8s.aet.cit.tum.de
        - prometheus-team-evil-jenkins.student.k8s.aet.cit.tum.de
