apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    app: postgres
    chart: team-evil-jenkins
    component: postgres-init
    heritage: Helm
    release: {{ .Release.Name }}
data:
  init.sql: |-
    CREATE DATABASE user_service_db;
    CREATE DATABASE location_service_db;
    CREATE DATABASE messaging_service_db;
    CREATE DATABASE matching_service_db;
