---
- hosts: webservers
  become: yes
  tasks:
    - name: "Wait for the server to be ready"
      wait_for_connection:
        timeout: 120
        sleep: 10

    - name: "Install Docker Compose"
      shell: "curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
      args:
        creates: /usr/local/bin/docker-compose

    - name: "Create application directory on the server"
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: "Copy docker-compose.yml to the server"
      copy:
        src: ./docker-compose.yml
        dest: /opt/app/docker-compose.yml

    - name: "Copy configuration directories to the server"
      copy:
        src: ../{{ item }}
        dest: /opt/app/
      with_items:
        - nginx
        - prometheus
        - grafana
        - postgres

    - name: "Copy .env file for environment variables"
      copy:
        src: ../.env
        dest: /opt/app/.env

    - name: "Stop and disable the default httpd service"
      service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: "Ensure Docker service is in a clean state"
      service:
        name: docker
        state: restarted

    - name: "Log in to GitHub Container Registry"
      shell: "echo {{ ghcr_pat }} | docker login ghcr.io -u {{ ghcr_username }} --password-stdin"
      no_log: true 

    - name: "Deploy application stack with Docker Compose"
      shell: |
        cd /opt/app
        # This command stops and removes any containers from a previous run.
        /usr/local/bin/docker-compose down
        # Step 1: Pull the latest images from the registry
        /usr/local/bin/docker-compose pull
        # Step 2: Start all services in detached mode.
        /usr/local/bin/docker-compose up -d --force-recreate
