server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,prometheus
  prometheus:
    enabled: true

my-service:
  message: Hello from Default Profile!

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: development
---

spring:
  config:
    activate:
      on-profile: development

my-service:
  message: Hello from Development!

---
spring:
  config:
    activate:
      on-profile: production

my-service:
  message: Hello from Production!
