name: Deploy to Kubernetes via Helm

on:
  push:
    branches:
      - main
on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Write kubeconfig from secret
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Helm upgrade/install
        run: |
          helm upgrade --install team-evil-jenkins ./helm/team-evil-jenkins -n team-evil-jenkins --set redeploy=$(date +%s) --debug
