name: Deploy Manually to Kubernetes via Helm

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Write kubeconfig from secret
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Create/Update Auth0 K8s Secret
        run: |
          kubectl create secret generic auth0-secrets \
            --from-literal=AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} \
            --from-literal=AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} \
            --from-literal=AUTH0_DOMAIN=${{ vars.AUTH0_DOMAIN }} \
            --from-literal=AUTH0_AUDIENCE=${{ vars.AUTH0_AUDIENCE }} \
            --from-literal=VITE_AUTH0_DOMAIN=${{ vars.AUTH0_DOMAIN }} \
            --from-literal=VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} \
            --from-literal=VITE_AUTH0_AUDIENCE=${{ vars.AUTH0_AUDIENCE }} \
            -n team-evil-jenkins --dry-run=client -o yaml | kubectl apply -f -

      - name: Create/Update GenAI K8s Secret
        run: |
          kubectl create secret generic genai-secrets \
            --from-literal=OPENWEBUI_URL="${{ vars.OPENWEBUI_URL }}" \
            --from-literal=OPENWEBUI_API_KEY="${{ secrets.OPENWEBUI_API_KEY }}" \
            -n team-evil-jenkins --dry-run=client -o yaml | kubectl apply -f -

      - name: Helm upgrade/install
        run: |
          helm upgrade --install team-evil-jenkins ./helm/team-evil-jenkins -n team-evil-jenkins --set redeploy=$(date +%s) --debug
